# Generated by Django 3.2.23 on 2023-11-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
    ]
