# Generated by Django 3.2.23 on 2023-11-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
    ]
