# Generated by Django 3.2.23 on 2023-11-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_flight_passenger_schedule_transactions'),
    ]

    operations = [
    ]
