# Generated by Django 3.2.23 on 2023-11-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_flight_passenger_schedule_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='title',
            field=models.CharField(max_length=3),
        ),
    ]
