# Generated by Django 3.2.23 on 2023-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_flight_passenger_schedule_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='seatmap',
            field=models.CharField(default='000000000000000000000000', max_length=24),
        ),
    ]
