# Generated by Django 3.2.23 on 2023-11-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_flight_passenger_schedule_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
