# Generated by Django 3.2.23 on 2023-11-08 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_employee_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_test_flag',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
        migrations.AddField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.employer'),
        ),
    ]
