# Generated by Django 3.2.23 on 2023-11-14 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20231114_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='inbound',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='outbound',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='principal_contact_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='principal_email',
        ),
        migrations.AddField(
            model_name='booking',
            name='inbound_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='inbound_flightno',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='outbound_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='outbound_flightno',
            field=models.CharField(default='', max_length=6),
        ),
    ]
