# Generated by Django 3.2.23 on 2023-11-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_flight_passenger_schedule_transactions'),
    ]

    operations = [
    ]
