# Generated by Django 3.2.23 on 2023-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_schedule_seatmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(default='user', max_length=80),
        ),
    ]
