# Generated by Django 3.2.23 on 2023-11-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_transaction_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='passenger',
            name='inbound_seat_number',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='passenger',
            name='outbound_seat_number',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
