# Generated by Django 3.2.23 on 2023-11-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20231118_0320'),
    ]

    operations = [
    ]
