# Generated by Django 3.2.23 on 2023-11-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_outbound_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='username',
            field=models.CharField(default='username', max_length=40),
        ),
    ]
