# Generated by Django 3.2.23 on 2023-11-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20231118_0347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ticket_class',
        ),
        migrations.AddField(
            model_name='schedule',
            name='seatmap',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
