# Generated by Django 3.2.23 on 2023-11-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20231121_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='pax_order_number',
            new_name='order_number',
        ),
    ]
