# Generated by Django 3.2.23 on 2023-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_order_number_passenger_pax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='status',
            field=models.CharField(max_length=4),
        ),
    ]
